### ISSUE TITLE
"Access is denied" with Windows 8.1

### ISSUE THREAD

**Issue by nisehime** [wa2c/cifs-documents-provider#24]
Hello.

I set up shared folder on windows without password. When I'm trying to connect to my PC from your app it show "access is denied error", it doesn't show folders too. I also check "anonymous" mark - still doesn't work.
Total Commander's LAN plugin doesn't have this issue. It looks like it uses Guest account to login, however when I use this in CIFS documents provider it gives me thies error: "IPC signing is enforced, but no signing is available"

**Comment by YanceyChiew** [comment]
The minimum smb version supported by this APP is 2.02, the signature algorithm supported by smb increases with the version number, please check the smb version you installed in Windows optional features.

**Comment by YanceyChiew** [comment]
Well, successfully reproduced the issue.

It doesn't just happen on win8.1, I have the same problem on my win11, it should be related to the upstream library.

It's just that when you mentioned anonymous access, I didn't realize it meant explicitly putting 'guest' in the username field, I got the same error when I tried to do that.

The source of the problem is not yet clear, but the error mentioned in this issue is related to the guest username. For some [reason](https://github.com/AgNO3/jcifs-ng/blob/84b10d06d332b8c0bea2919b8784c726c280aaee/CHANGELOG.txt#L32-L37), jcifs-ng uses JCIFSGUEST instead of Guest as the username when the guest logs in. 

In addition, another _parameter error_ error may be caused by jcifs-ng not properly handling passwordless login, see [this](https://github.com/AgNO3/jcifs-ng/issues/226), the specific reason for this error is not found, but it can be ignored through configuration properties as in the issue I cited.



```git
diff --git a/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/data/CifsClient.kt b/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/data/CifsClient.kt
index e3b1c70..3844176 100644
--- a/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/data/CifsClient.kt
+++ b/app/src/main/java/com/wa2c/android/cifsdocumentsprovider/data/CifsClient.kt
@@ -34,6 +34,8 @@ class CifsClient @Inject constructor() {
             setProperty("jcifs.smb.client.responseTimeout", READ_TIMEOUT.toString())
             setProperty("jcifs.smb.client.connTimeout", CONNECTION_TIMEOUT.toString())
             setProperty("jcifs.smb.client.dfs.disabled", (!enableDfs).toString())
+            setProperty("jcifs.smb.client.guestUsername", "Guest")
+            setProperty("jcifs.smb.client.disableSpnegoIntegrity", "true")
         }

         val context = BaseContext(PropertyConfiguration(property)).let {
```

After adding the above two lines of properties, smb share can be accessed by guest user, should work as a temporary around.

**Comment by nisehime** [comment]
> It's just that when you mentioned anonymous access, I didn't realize it meant explicitly putting 'guest' in the username field

I tried both anonymous and 'guest' logins. With anonymous (or any passwordless account) I was getting "access is denied", with 'guest' it's the other error I described in OP post.

Thanks for your solution.

**Comment by nisehime** [comment]
I think on Windows it's normal that you can't use passwordless accounts other than 'Guest' for SMB auth (by default, but there are settings in Group Policies to change that), so this can be taken in consideration.

**Comment by wa2c** [comment]
@nisehime 

I checked the problem using [Microsoft official Virtual Machine  for IE Testing](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) installed Windows 8.1 .

I create "test" user without password on VM.
And I tried to connect to the VM. It was failed  with message "User account restriction".

Next, I changed  following setting in Windows Local Security Policy.
[ Security Settings/Local Policies/Security Options ]
->  [ Accounts: Limit localaccount use of blank password to console login only. ]
**Enabled -> Disabled**

![image](https://user-images.githubusercontent.com/14200387/170350046-8126ab31-4df0-4b69-85d4-802d34d5a655.png)

After that, the connection was successful.

Is this the same as your problem?

**Comment by YanceyChiew** [comment]
Although I didn't have locate how `withGuestCrendentials()` brings `digest=null`, but the problem has been solved, via disable `ipcSigningEnforced` for guest.

After applying this change, if the username is guest, the guest credentials will be used _(the default behavior of jcifs-ng)_ . The difference from the previous workaround is that this time is a real guest login. The username and password themselves are meaningless and are only used to choose whether to use the guest credentials. For example, it is also possible to use guest credentials when both username and password are empty, but I see that in an earlier commit, they have been used to select `withAnonymousCredentials` already.

**Comment by YanceyChiew** [comment]
> but I see that in an earlier commit, they have been used to select `withAnonymousCredentials` already.

My bad, the commit I mentioned above was also intended to support guest, and up until then guest credentials were not automatically selected even if the user name was guest. Given this, I think it's a reasonable choice to use the empty username and password to select guest credentials, since there is already a checkbox designed specifically for anonymous credentials.
