### ISSUE TITLE
Bad Shared URI design

### ISSUE THREAD

**Issue by wa2c** [wa2c/cifs-documents-provider#4]
This app has bad URI design.

1. Connection A
* Host: 192.168.0.1
* Folder: test
↓
* SMB URI = smb://192.168.0.1/test/
* Shared URI = content://com.wa2c.android.cifsdocumentsprovider.documents/tree/192.168.0.1%2Ftest%2F

2. Connection B
* Host: 192.168.0.1
* Folder: test/app
↓
* URI = smb://192.168.0.1/test/app/
* content://com.wa2c.android.cifsdocumentsprovider.documents/tree/192.168.0.1%2Ftest%2Fapp%2F

If you select a file "smb://192.168.0.1/test/app/file.txt", this app can't know which setting to use.
(Beacause of shared URI is  content://com.wa2c.android.cifsdocumentsprovider.documents/tree/192.168.0.1%2Ftest%2Fapp%2Ffile.txt)

## Correct URL design

Separate connection and selected path with ":" (%3A).

1. Connection A
Shared URI = content://com.wa2c.android.cifsdocumentsprovider.documents/tree/192.168.0.1%2Ftest%3Aapp%2Ffile.txt

2. Connection B
Shared URI = content://com.wa2c.android.cifsdocumentsprovider.documents/tree/192.168.0.1%2Ftest%2Fapp%3Afile.txt

**Comment by YanceyChiew** [comment]
I think there is no need to worry about uri confusion.
Under the same domain name 192.168.0.1, the test/app folder is supposed be a subdirectory of test, therefore, the two uri should originally point to the same file.
The test folder is the first-level node under the shared root directory of 192.168.0.1. There should be no first-level node with the same name test. The shared directory with the same name will be automatically renamed with an ordinal suffix by cifs server.

However, in actual use, there may be situations where the same IP/domain name points to different hosts, so if you want to rewrite the uri construction logic, I recommend using aliases instead of host/ directories(default).

**Comment by wa2c** [comment]
Thank you!
I will investigate them.

**Comment by wa2c** [comment]
It is solved in Ver.2.1.0.
I changed shared URI structure.
Close this issue.
